

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: frontend:latest
    ports:
      - 8501:8501
    networks:
      - project_network
    depends_on:
      - backend
    # volumes:
    #   - ./frontend:/app/backend


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      shm_size: '8gb'
    shm_size: '8gb'
    image: backend:latest
    ports:
      - 8080:8080
    networks:
      - project_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
      
networks:
  project_network:

